language: ruby
rvm:
  - 2.2.1
branches:
  only:
  - release
env:
  - secure: "hzsoLvfsveyRFbyykjIfDyLZzMLM72Ar6AOEUxRwhpxMBoXeX9Y9T0Cl9j3jwTN3FAmA8zuqpSIe42geFJIRjnYzKDLcpik3sM8Avc5kqJbYhwkBKfYJYzoQ/aYYbe0yAZ3/USOyPU9TbKH8jvQqkvCu9c/EQPvTSb/aXaLE6MA="
script: ./scripts/build
after_success: ./scripts/deploy
